"""
src/setup.py
-------------
Kairo Interactive Setup Wizard

An interactive command-line wizard that guides the user through initial
configuration. It collects required and optional values, validates them,
and writes a .env file to the project root.

Usage:
    python src/setup.py

The wizard will:
    1. Check for an existing .env file and offer to update or recreate it.
    2. Prompt for required Discord credentials (bot token, client ID/secret).
    3. Prompt for optional settings (prefix, log level, API, database path).
    4. Optionally detect Termux and suggest Termux-specific requirements.
    5. Write the .env file.
    6. Optionally install Python dependencies.

Run this before starting Kairo for the first time.
"""

import os
import sys
import subprocess
import platform
from pathlib import Path
from typing import Optional

# Project root is one level above this file.
_PROJECT_ROOT = Path(__file__).parent.parent.resolve()
_ENV_FILE = _PROJECT_ROOT / ".env"


# ------------------------------------------------------------------ #
# Helpers                                                              #
# ------------------------------------------------------------------ #

def _print_header() -> None:
    print()
    print("=" * 60)
    print("  Kairo Setup Wizard")
    print("  A modern, self-hostable Discord platform.")
    print("=" * 60)
    print()


def _prompt(
    label: str,
    default: Optional[str] = None,
    secret: bool = False,
    required: bool = True,
) -> str:
    """
    Prompt the user for a value.

    Args:
        label:    The question to display.
        default:  Default value shown in brackets; used if the user presses Enter.
        secret:   If True, masks input (for tokens/secrets).
        required: If True and no value is entered (and no default), re-prompt.

    Returns:
        The entered or default value.
    """
    display_default = f" [{default}]" if default else ""
    display_required = " (required)" if required and not default else ""
    prompt_str = f"  {label}{display_required}{display_default}: "

    while True:
        if secret:
            import getpass
            value = getpass.getpass(prompt_str)
        else:
            value = input(prompt_str).strip()

        if not value:
            if default is not None:
                return default
            if not required:
                return ""
            print(f"  ⚠️  This field is required. Please enter a value.")
            continue
        return value


def _confirm(label: str, default: bool = True) -> bool:
    """Yes/no confirmation prompt."""
    yn = "Y/n" if default else "y/N"
    value = input(f"  {label} [{yn}]: ").strip().lower()
    if not value:
        return default
    return value in ("y", "yes")


def _detect_termux() -> bool:
    """Return True if running inside Termux on Android."""
    return os.path.exists("/data/data/com.termux") or "com.termux" in os.environ.get("PREFIX", "")


def _check_existing_env() -> bool:
    """
    Check if a .env file already exists and ask whether to overwrite it.

    Returns:
        True if setup should proceed, False to abort.
    """
    if not _ENV_FILE.exists():
        return True

    print(f"  ⚠️  A .env file already exists at: {_ENV_FILE}")
    return _confirm("Do you want to overwrite it?", default=False)


def _write_env(values: dict) -> None:
    """Write the collected values to the .env file."""
    lines = [
        "# Kairo Configuration",
        "# Generated by src/setup.py — edit as needed.",
        "# See docs/configuration.md for full documentation.",
        "",
        "# ── Discord ──────────────────────────────────",
        f"BOT_TOKEN={values.get('BOT_TOKEN', '')}",
        f"CLIENT_ID={values.get('CLIENT_ID', '')}",
        f"CLIENT_SECRET={values.get('CLIENT_SECRET', '')}",
        f"BOT_PREFIX={values.get('BOT_PREFIX', '!')}",
        "",
        "# Development guild for instant slash command sync.",
        "# Leave empty for global sync (production).",
        f"DEV_GUILD_ID={values.get('DEV_GUILD_ID', '')}",
        "",
        "# ── Database ─────────────────────────────────",
        f"DB_PATH={values.get('DB_PATH', 'data/kairo.db')}",
        "",
        "# ── Logging ──────────────────────────────────",
        "# Levels: DEBUG, INFO, WARNING, ERROR",
        f"LOG_LEVEL={values.get('LOG_LEVEL', 'INFO')}",
        "",
        "# ── API Server ───────────────────────────────",
        f"API_HOST={values.get('API_HOST', '127.0.0.1')}",
        f"API_PORT={values.get('API_PORT', '8080')}",
        f"API_SECRET={values.get('API_SECRET', '')}",
        "",
        "# ── Dashboard / OAuth2 ───────────────────────",
        f"DASHBOARD_URL={values.get('DASHBOARD_URL', 'http://localhost:5173')}",
        "# OAUTH_REDIRECT=  # Defaults to DASHBOARD_URL/auth/callback",
        "",
        "# ── Runtime ──────────────────────────────────",
        "# Set to true to enable debug mode (verbose logging, dev guild sync).",
        f"DEBUG={values.get('DEBUG', 'false')}",
    ]

    _ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n  ✅ .env file written to: {_ENV_FILE}")


def _install_dependencies() -> None:
    """Offer to install Python dependencies via pip."""
    req_file = _PROJECT_ROOT / "requirements.txt"
    if not req_file.exists():
        print("  ⚠️  requirements.txt not found. Skipping dependency installation.")
        return

    print()
    if not _confirm("Install Python dependencies from requirements.txt?"):
        print("  Skipping. Run 'pip install -r requirements.txt' manually.")
        return

    is_termux = _detect_termux()
    pip_cmd = [sys.executable, "-m", "pip", "install", "-r", str(req_file)]

    if is_termux:
        print("  📱 Termux detected. Note: some packages may need additional setup.")
        termux_req = _PROJECT_ROOT / "requirements-termux.txt"
        if termux_req.exists() and _confirm("Also install Termux-specific requirements?"):
            subprocess.run([sys.executable, "-m", "pip", "install", "-r", str(termux_req)], check=False)

    print(f"  Running: {' '.join(pip_cmd)}")
    result = subprocess.run(pip_cmd)
    if result.returncode == 0:
        print("  ✅ Dependencies installed successfully.")
    else:
        print("  ❌ Dependency installation failed. Check the output above.")


# ------------------------------------------------------------------ #
# Main wizard                                                          #
# ------------------------------------------------------------------ #

def run_wizard() -> None:
    """Run the interactive setup wizard."""
    _print_header()

    print("  This wizard will create a .env configuration file for Kairo.")
    print("  You will need:")
    print("    - A Discord bot token (discord.com/developers/applications)")
    print("    - Your Discord application's Client ID and Client Secret")
    print()

    if not _check_existing_env():
        print("\n  Setup cancelled.")
        return

    values: dict = {}

    # ---------------------------------------------------------------- #
    # Discord credentials                                               #
    # ---------------------------------------------------------------- #
    print("── Discord Credentials ──────────────────────────")
    print("  Get these from: https://discord.com/developers/applications")
    print()
    values["BOT_TOKEN"]     = _prompt("Bot Token", secret=True)
    values["CLIENT_ID"]     = _prompt("Client ID")
    values["CLIENT_SECRET"] = _prompt("Client Secret", secret=True)
    values["BOT_PREFIX"]    = _prompt("Command prefix", default="!")

    print()
    print("── Development Settings ─────────────────────────")
    print("  Optional: enter your development server's ID for instant slash command sync.")
    print("  Leave empty for global sync (use in production).")
    values["DEV_GUILD_ID"] = _prompt("Dev Guild ID", default="", required=False)

    # ---------------------------------------------------------------- #
    # Database                                                          #
    # ---------------------------------------------------------------- #
    print()
    print("── Database ─────────────────────────────────────")
    values["DB_PATH"] = _prompt("Database file path", default="data/kairo.db")

    # ---------------------------------------------------------------- #
    # Logging                                                           #
    # ---------------------------------------------------------------- #
    print()
    print("── Logging ──────────────────────────────────────")
    print("  Levels: DEBUG, INFO, WARNING, ERROR")
    values["LOG_LEVEL"] = _prompt("Log level", default="INFO")

    # ---------------------------------------------------------------- #
    # API server                                                        #
    # ---------------------------------------------------------------- #
    print()
    print("── API Server ───────────────────────────────────")
    print("  The API server allows the web dashboard to communicate with the bot.")
    if _confirm("Configure API server?", default=False):
        values["API_HOST"]   = _prompt("API host", default="127.0.0.1")
        values["API_PORT"]   = _prompt("API port", default="8080")
        values["API_SECRET"] = _prompt("API secret key", secret=True)
    else:
        values["API_HOST"]   = "127.0.0.1"
        values["API_PORT"]   = "8080"
        values["API_SECRET"] = ""

    # ---------------------------------------------------------------- #
    # Dashboard                                                         #
    # ---------------------------------------------------------------- #
    print()
    print("── Dashboard ────────────────────────────────────")
    values["DASHBOARD_URL"] = _prompt(
        "Dashboard public URL",
        default="http://localhost:5173",
    )

    # ---------------------------------------------------------------- #
    # Debug mode                                                        #
    # ---------------------------------------------------------------- #
    print()
    print("── Runtime ──────────────────────────────────────")
    enable_debug = _confirm("Enable debug mode? (Recommended: No for production)", default=False)
    values["DEBUG"] = "true" if enable_debug else "false"

    # ---------------------------------------------------------------- #
    # Write .env                                                        #
    # ---------------------------------------------------------------- #
    print()
    print("── Writing configuration ────────────────────────")
    _write_env(values)

    # ---------------------------------------------------------------- #
    # Install dependencies                                              #
    # ---------------------------------------------------------------- #
    print()
    print("── Dependencies ─────────────────────────────────")
    _install_dependencies()

    # ---------------------------------------------------------------- #
    # Done                                                              #
    # ---------------------------------------------------------------- #
    print()
    print("=" * 60)
    print("  Setup complete!")
    print()
    print("  Start Kairo:")
    print("    python src/run.py")
    print()
    print("  Start with the API server:")
    print("    python src/run.py --with-api")
    print()
    print("  Documentation:")
    print("    docs/getting-started.md")
    print("=" * 60)
    print()


if __name__ == "__main__":
    try:
        run_wizard()
    except KeyboardInterrupt:
        print("\n\n  Setup cancelled.")
        sys.exit(0)
